"""Aumenta tamanho do campo image_file para URL

Revision ID: 522d3f6d99e6
Revises: c5a365ea09c4
Create Date: 2025-09-19 18:24:00.225343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522d3f6d99e6'
down_revision = 'c5a365ea09c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
